/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Custom Window
 #	author : miyako
 #	2017/01/27
 #
 # --------------------------------------------------------------------------------*/



// --- Custom Window
void SET_WINDOW_TRANSPARENT(sLONG_PTR *pResult, PackagePtr pParams);
