/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Custom Window
 #	author : miyako
 #	2017/01/27
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#import <objc/runtime.h>
#import <AppKit/AppKit.h>

// --- Custom Window
void SET_WINDOW_TRANSPARENT(sLONG_PTR *pResult, PackagePtr pParams);
void ___SET_WINDOW_TRANSPARENT(PA_PluginParameters params);
