/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Custom-Window.h
 #	source generated by 4D Plugin Wizard
 #	Project : Custom Window
 #	author : miyako
 #	2020/11/30
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_CUSTOM_WINDOW_H
#define PLUGIN_CUSTOM_WINDOW_H

#include "4DPluginAPI.h"

#import <objc/runtime.h>
#import <AppKit/AppKit.h>

#pragma mark -

void SET_WINDOW_TRANSPARENT(PA_PluginParameters params);
void SET_WINDOW_ALPHA(PA_PluginParameters params);
void Get_window_alpha(PA_PluginParameters params);

#endif /* PLUGIN_CUSTOM_WINDOW_H */
